"""refactor(memory): standardize scope field naming

Revision ID: 7dc6b0967671
Revises: 7be8cb744f52
Create Date: 2025-11-20 15:06:40.167143

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dc6b0967671"
down_revision: Union[str, None] = "7be8cb744f52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rename subject_role column to scope
    op.alter_column("memory_records", "subject_role", new_column_name="scope")
    # Recreate index with new column name
    op.drop_index(op.f("ix_memory_records_subject_role"), table_name="memory_records")
    op.create_index(op.f("ix_memory_records_scope"), "memory_records", ["scope"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memory_records", sa.Column("subject_role", sa.VARCHAR(length=32), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_memory_records_scope"), table_name="memory_records")
    op.create_index(op.f("ix_memory_records_subject_role"), "memory_records", ["subject_role"], unique=False)
    op.drop_column("memory_records", "scope")
    # ### end Alembic commands ###
