"""restructure_memory

Revision ID: 85ce880fe522
Revises: 20251206_memory_insights
Create Date: 2025-11-19 07:27:35.867748

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ce880fe522'
down_revision: Union[str, None] = '20251206_memory_insights'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('partner_id', sa.String(length=128), nullable=True),
    sa.Column('subject_role', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('retention', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('entities', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_category'), 'memory_records', ['category'], unique=False)
    op.create_index(op.f('ix_memory_records_partner_id'), 'memory_records', ['partner_id'], unique=False)
    op.create_index(op.f('ix_memory_records_retention'), 'memory_records', ['retention'], unique=False)
    op.create_index(op.f('ix_memory_records_subject_role'), 'memory_records', ['subject_role'], unique=False)
    op.create_index(op.f('ix_memory_records_thread_id'), 'memory_records', ['thread_id'], unique=False)
    op.create_index('ix_memory_records_user_hash', 'memory_records', ['user_id', 'content_hash'], unique=True)
    op.create_index(op.f('ix_memory_records_user_id'), 'memory_records', ['user_id'], unique=False)
    op.create_table('conversation_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version', sa.String(length=64), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Integer(), nullable=False),
    sa.Column('expression_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('improvement_tips', sa.Text(), nullable=True),
    sa.Column('evaluation_raw', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_evaluations_conversation_id'), 'conversation_evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_evaluations_user_id'), 'conversation_evaluations', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang_code', sa.String(length=16), nullable=False),
    sa.Column('translation_text', sa.Text(), nullable=True),
    sa.Column('translation_lang_code', sa.String(length=16), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['conversation_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_conversation_messages_conversation_seq')
    )
    op.create_index('ix_conversation_messages_conversation_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('is_overall', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedback_conversation_id'), 'message_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_user_id'), 'message_feedback', ['user_id'], unique=False)
    op.add_column('account_conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account_conversations', sa.Column('message_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('account_conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('account_conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_account_conversations_session_id'), table_name='account_conversations')
    op.drop_column('account_conversations', 'feedback')
    op.drop_column('account_conversations', 'session_id')
    op.drop_column('account_conversations', 'scores')
    op.drop_column('account_conversations', 'memory_insights')
    op.drop_column('account_conversations', 'messages')
    op.drop_column('account_conversations', 'participant_snapshot')
    op.alter_column('conversation_partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_partners', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_partners', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversation_partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('account_conversations', sa.Column('participant_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('account_conversations', sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('account_conversations', sa.Column('memory_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('account_conversations', sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('account_conversations', sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('account_conversations', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_account_conversations_session_id'), 'account_conversations', ['session_id'], unique=True)
    op.alter_column('account_conversations', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('account_conversations', 'updated_at')
    op.drop_column('account_conversations', 'message_count')
    op.drop_column('account_conversations', 'last_message_at')
    op.drop_index(op.f('ix_message_feedback_user_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_conversation_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_evaluations_user_id'), table_name='conversation_evaluations')
    op.drop_index(op.f('ix_conversation_evaluations_conversation_id'), table_name='conversation_evaluations')
    op.drop_table('conversation_evaluations')
    op.drop_index(op.f('ix_memory_records_user_id'), table_name='memory_records')
    op.drop_index('ix_memory_records_user_hash', table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_thread_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_subject_role'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_retention'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_partner_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_category'), table_name='memory_records')
    op.drop_table('memory_records')
    # ### end Alembic commands ###
