"""add persona location and occupation fields

Revision ID: 1252a6373cf3
Revises: a44b691abab4
Create Date: 2025-11-22 16:13:59.794204

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1252a6373cf3'
down_revision: Union[str, None] = 'a44b691abab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_partners', sa.Column('persona_occupation', sa.String(length=128), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_city', sa.String(length=128), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_country', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_partners', 'persona_country')
    op.drop_column('conversation_partners', 'persona_city')
    op.drop_column('conversation_partners', 'persona_occupation')
    # ### end Alembic commands ###

