"""add partner persona fields

Revision ID: a44b691abab4
Revises: 9c26f985f972
Create Date: 2025-11-22 15:19:07.834517

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44b691abab4'
down_revision: Union[str, None] = '9c26f985f972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_partners', sa.Column('persona_age', sa.String(length=32), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_gender', sa.String(length=32), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_relationship', sa.String(length=64), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_background', sa.Text(), nullable=True))
    op.add_column('conversation_partners', sa.Column('persona_interests', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_memory_records_embedding_hnsw'), table_name='memory_records', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_memory_records_embedding_hnsw'), 'memory_records', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('conversation_partners', 'persona_interests')
    op.drop_column('conversation_partners', 'persona_background')
    op.drop_column('conversation_partners', 'persona_relationship')
    op.drop_column('conversation_partners', 'persona_gender')
    op.drop_column('conversation_partners', 'persona_age')
    # ### end Alembic commands ###

