"""initial_commit

Revision ID: 1092246c2f6b
Revises: 
Create Date: 2025-11-19 23:43:17.107270

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1092246c2f6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learning_lang', sa.String(length=32), nullable=True),
    sa.Column('native_lang', sa.String(length=32), nullable=True),
    sa.Column('language_level', sa.String(length=32), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=True),
    sa.Column('subscription_plan', sa.String(length=32), nullable=True),
    sa.Column('subscription_interval', sa.String(length=16), nullable=True),
    sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_exempt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_account_users_email'), 'account_users', ['email'], unique=True)
    op.create_index(op.f('ix_account_users_verification_token'), 'account_users', ['verification_token'], unique=True)
    op.create_table('conversation_partners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('learning_lang', sa.String(length=32), nullable=True),
    sa.Column('native_lang', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('extra_metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_partners_slug'), 'conversation_partners', ['slug'], unique=False)
    op.create_index(op.f('ix_conversation_partners_user_id'), 'conversation_partners', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('account_conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('partner_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('learning_lang', sa.String(length=32), nullable=True),
    sa.Column('native_lang', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['conversation_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_conversations_partner_id'), 'account_conversations', ['partner_id'], unique=False)
    op.create_index(op.f('ix_account_conversations_user_id'), 'account_conversations', ['user_id'], unique=False)
    op.create_table('conversation_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version', sa.String(length=64), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Integer(), nullable=False),
    sa.Column('expression_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('improvement_tips', sa.Text(), nullable=True),
    sa.Column('evaluation_raw', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_evaluations_conversation_id'), 'conversation_evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_evaluations_user_id'), 'conversation_evaluations', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.String(length=64), nullable=True),
    sa.Column('utterance_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang_code', sa.String(length=16), nullable=False),
    sa.Column('translation_text', sa.Text(), nullable=True),
    sa.Column('translation_lang_code', sa.String(length=16), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['conversation_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_conversation_messages_conversation_seq')
    )
    op.create_index('ix_conversation_messages_conversation_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_index('ix_conversation_messages_utterance_id', 'conversation_messages', ['utterance_id'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('partner_id', sa.String(length=128), nullable=True),
    sa.Column('subject_role', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('retention', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('entities', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_category'), 'memory_records', ['category'], unique=False)
    op.create_index(op.f('ix_memory_records_conversation_id'), 'memory_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_records_partner_id'), 'memory_records', ['partner_id'], unique=False)
    op.create_index(op.f('ix_memory_records_retention'), 'memory_records', ['retention'], unique=False)
    op.create_index(op.f('ix_memory_records_subject_role'), 'memory_records', ['subject_role'], unique=False)
    op.create_index('ix_memory_records_user_hash', 'memory_records', ['user_id', 'content_hash'], unique=True)
    op.create_index(op.f('ix_memory_records_user_id'), 'memory_records', ['user_id'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('is_overall', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['account_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedback_conversation_id'), 'message_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_user_id'), 'message_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedback_user_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_conversation_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_memory_records_user_id'), table_name='memory_records')
    op.drop_index('ix_memory_records_user_hash', table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_subject_role'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_retention'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_partner_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_conversation_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_category'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index('ix_conversation_messages_utterance_id', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_evaluations_user_id'), table_name='conversation_evaluations')
    op.drop_index(op.f('ix_conversation_evaluations_conversation_id'), table_name='conversation_evaluations')
    op.drop_table('conversation_evaluations')
    op.drop_index(op.f('ix_account_conversations_user_id'), table_name='account_conversations')
    op.drop_index(op.f('ix_account_conversations_partner_id'), table_name='account_conversations')
    op.drop_table('account_conversations')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_conversation_partners_user_id'), table_name='conversation_partners')
    op.drop_index(op.f('ix_conversation_partners_slug'), table_name='conversation_partners')
    op.drop_table('conversation_partners')
    op.drop_index(op.f('ix_account_users_verification_token'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_email'), table_name='account_users')
    op.drop_table('account_users')
    # ### end Alembic commands ###

