"""add_subscription_cancel_fields

Revision ID: 7be8cb744f52
Revises: 1092246c2f6b
Create Date: 2025-11-20 00:08:10.354699

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be8cb744f52'
down_revision: Union[str, None] = '1092246c2f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('subscription_cancel_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('account_users', sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_users', 'subscription_cancel_at_period_end')
    op.drop_column('account_users', 'subscription_cancel_at')
    # ### end Alembic commands ###

