"""remove_unused_partner_fields

Revision ID: 68238d42e61d
Revises: 1252a6373cf3
Create Date: 2025-11-22 19:54:26.524221

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68238d42e61d"
down_revision: Union[str, None] = "1252a6373cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_partners_slug"), table_name="conversation_partners")
    op.drop_column("conversation_partners", "slug")
    op.drop_column("conversation_partners", "is_system")
    op.drop_column("conversation_partners", "extra_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_partners",
        sa.Column("extra_metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column("conversation_partners", sa.Column("is_system", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column(
        "conversation_partners", sa.Column("slug", sa.VARCHAR(length=64), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_conversation_partners_slug"), "conversation_partners", ["slug"], unique=False)
    # ### end Alembic commands ###
