import linguiConfig from './lingui.config';
import { I18n, i18n } from '@lingui/core';

const { locales } = linguiConfig;
export const defaultLocale = 'en';

// optionally use a stricter union type
type SupportedLocales = string;

async function loadCatalog(
  locale: SupportedLocales
): Promise<{ [k: string]: any }> {
  try {
    // Import the compiled .js file (generated by lingui compile)
    const mod = await import(`@locales/${locale}.js`);

    // The compiled .js exports: module.exports={messages:JSON.parse("...")}
    const messages = mod.messages || mod.default?.messages || mod.default || {};

    return { [locale]: messages };
  } catch (error) {
    console.error(`[Lingui] Failed to load catalog for ${locale}:`, error);
    return { [locale]: {} };
  }
}
const catalogs = await Promise.all(locales.map(loadCatalog));

// transform array of catalogs into a single object
export const allMessages = catalogs.reduce<Record<string, any>>(
  (acc: Record<string, any>, oneCatalog: Record<string, any>) => {
    return { ...acc, ...oneCatalog };
  },
  {}
);

// 경로에서 로케일을 추출하는 함수
export function getLocaleFromPath(path: string): string {
  if (!path) return defaultLocale;

  const segments = path.split('/').filter(Boolean);
  const firstSegment = segments[0];

  if (locales.includes(firstSegment ?? '')) {
    return firstSegment ?? '';
  }

  return defaultLocale;
}

// For Lingui v5, initialize the global i18n instance
// This ensures messages are loaded during server rendering
export function initializeServerI18n(locale: SupportedLocales = defaultLocale) {
  const effectiveLocale = locale || defaultLocale;
  const messages = allMessages[effectiveLocale] || {};

  if (Object.keys(messages).length > 0) {
    i18n.load(effectiveLocale, messages);
    i18n.activate(effectiveLocale);
  } else {
    console.warn(`[Lingui] No messages found for locale: ${effectiveLocale}`);
  }
  return i18n;
}

// Legacy function for backward compatibility
export const getI18nInstance = (locale: SupportedLocales): I18n => {
  // For v5, we use the global instance instead of creating multiple instances
  const effectiveLocale = locale || defaultLocale;
  const messages = allMessages[effectiveLocale] || {};

  if (Object.keys(messages).length > 0) {
    i18n.load(effectiveLocale, messages);
    i18n.activate(effectiveLocale);
  } else {
    console.warn(`[Lingui] No messages found for locale: ${effectiveLocale}`);
  }
  return i18n;
};
